# Generated by Django 3.2.9 on 2021-11-26 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_clinic_fileupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='fileupload',
            field=models.FileField(upload_to='files'),
        ),
    ]
